apiVersion: v1
kind: ConfigMap
metadata:
  name: casdoor-conf
  namespace: casdoor
data:
  app.conf: |
    appname = casdoor
    httpport = 8000
    runmode = prod
    driverName = postgres
    dataSourceName = "user=__CASDOOR_DB_USER__ password=__CASDOOR_DB_PASS__ host=casdoor-postgres port=5432 sslmode=disable dbname=__CASDOOR_DB_NAME__"
    sessionOn = true
    origin = https://__CASDOOR_HOST__
    staticBaseUrl = "https://__CASDOOR_HOST__"
    logPostOnly = false
    isBehindProxy = true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: casdoor
  namespace: casdoor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casdoor
  template:
    metadata:
      labels:
        app: casdoor
    spec:
      containers:
        - name: casdoor
          image: __IMAGE_REPOSITORY__/docker.io.casbin.casdoor:__CASDOOR_VERSION__
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: conf
              mountPath: /conf
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 40
            periodSeconds: 20
      volumes:
        - name: conf
          configMap:
            name: casdoor-conf
---
apiVersion: v1
kind: Service
metadata:
  name: casdoor
  namespace: casdoor
spec:
  selector:
    app: casdoor
  ports:
    - port: 8000
      targetPort: 8000
