apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alloy-chart
  namespace: monitoring
spec:
  interval: 10m
  insecure: true
  secretRef:
    name: harbor-auth
  url: oci://harbor.test.baokuaiyun.com/baokuaiyun/alloy
  ref:
    tag: "1.13.0"