apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki-chart
  namespace: monitoring
spec:
  interval: 10m
  insecure: true
  secretRef:
    name: harbor-auth
  url: oci://harbor.test.baokuaiyun.com/baokuaiyun/loki
  ref:
    tag: "6.21.0"