#!/usr/bin/env bash
# 渲染平台入口域名的内网 DNS（单一来源，幂等）
#   - INGRESS_SERVICES × DOMAIN 生成 FQDN，统一指向入口 VIP（EFF_GATEWAY_VIP）
#   - 写入 kvm/br-prod.xml 的生成块（标记之间），virsh net-define 持久化
#   - virsh net-update --live 热生效（不重启网络/不断网）
#   - 同步宿主 /etc/hosts 托管块（自动去重旧的分散条目）
#   - 可选同步节点 /etc/hosts：UPDATE_NODE_HOSTS=1（默认 0，节点经 libvirt dnsmasq 解析）
#
# 用法: make ingress-dns
# 变量: EFF_GATEWAY_VIP/GATEWAY_VIP DOMAIN INGRESS_SERVICES NET_NAME NET_GATEWAY
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
NET_NAME="${NET_NAME:-br-prod}"
NET_GATEWAY="${NET_GATEWAY:-192.168.124.1}"
DOMAIN="${DOMAIN:-test.baokuaiyun.com}"
VIP="${EFF_GATEWAY_VIP:-${GATEWAY_VIP:-}}"
INGRESS_SERVICES="${INGRESS_SERVICES:-casdoor harbor gitlab grafana flux argocd}"
XML="${XML:-${ROOT}/kvm/br-prod.xml}"

if [ -z "$VIP" ]; then
  echo "[=] 入口 VIP 为空（prod 由 SLB 回写），跳过入口 DNS 渲染"
  exit 0
fi

HOSTS=()
for s in $INGRESS_SERVICES; do
  case "$s" in *.*) HOSTS+=("$s") ;; *) HOSTS+=("$s.$DOMAIN") ;; esac
done
echo "[+] 入口域名 -> ${VIP} : ${HOSTS[*]}"

# ---------- 1) 渲染 kvm/br-prod.xml 生成块 ----------
[ -f "$XML" ] || { echo "[!] 缺少 $XML"; exit 1; }
VIP="$VIP" HOSTS="${HOSTS[*]}" XML="$XML" python3 - <<'PY'
import os, re, sys
xml = os.environ["XML"]; vip = os.environ["VIP"]; hosts = os.environ["HOSTS"].split()
text = open(xml).read()
lines = ["    <!-- BEGIN ingress-dns (generated by scripts/render-ingress-dns.sh；勿手改) -->"]
for h in hosts:
    lines.append(f"    <dnsmasq:option value='host-record={h},{vip}'/>")
lines.append("    <!-- END ingress-dns -->")
block = "\n".join(lines)
pat = re.compile(r"(?ms)^[ \t]*<!-- BEGIN ingress-dns.*?-->\n.*?^[ \t]*<!-- END ingress-dns -->")
if not pat.search(text):
    sys.exit("[!] XML 缺少 ingress-dns 标记块")
new = pat.sub(lambda m: block, text, count=1)
if new != text:
    open(xml, "w").write(new)
    print("[+] 已更新", xml)
else:
    print("[=] XML 生成块无变化")
PY

# ---------- 2) 持久化 + 热应用 ----------
if command -v virsh >/dev/null 2>&1 && virsh net-info "$NET_NAME" >/dev/null 2>&1; then
  # 幂等 redefine：已存在时注入现有 uuid，避免 "已有 uuid" 冲突
  define_xml="$(mktemp)"
  cp "$XML" "$define_xml"
  net_uuid="$(virsh net-uuid "$NET_NAME" 2>/dev/null || true)"
  if [ -n "$net_uuid" ]; then
    DEFINE_XML="$define_xml" NET_UUID="$net_uuid" python3 - <<'PY'
import os, re
f = os.environ["DEFINE_XML"]; u = os.environ["NET_UUID"]
t = open(f).read()
if "<uuid>" not in t:
    t = re.sub(r"(<name>[^<]+</name>)", r"\1\n  <uuid>" + u + "</uuid>", t, count=1)
    open(f, "w").write(t)
PY
  fi
  virsh net-define "$define_xml" >/dev/null && echo "[+] net-define $NET_NAME"
  rm -f "$define_xml"
  for h in "${HOSTS[@]}"; do
    cur="$( (command -v dig >/dev/null 2>&1 && dig @"$NET_GATEWAY" "$h" +short) 2>/dev/null | head -1 || true)"
    if [ "$cur" = "$VIP" ]; then
      echo "    [=] $h 已正确 ($cur)"
    elif virsh net-update "$NET_NAME" add dns-host "<host ip='${VIP}'><hostname>${h}</hostname></host>" --live >/dev/null 2>&1; then
      echo "    live + $h"
    else
      echo "    [=] $h 已存在（live）"
    fi
  done
else
  echo "[=] 无 virsh/$NET_NAME，跳过 libvirt 应用"
fi

# ---------- 3) 宿主 /etc/hosts 托管块 ----------
if [ "${UPDATE_HOSTS:-auto}" != "0" ]; then
  HOSTS_FILE="${HOSTS_FILE:-/etc/hosts}" VIP="$VIP" HOSTS="${HOSTS[*]}" python3 - <<'PY'
import os, shutil
f = os.environ["HOSTS_FILE"]; vip = os.environ["VIP"]; hosts = os.environ["HOSTS"].split()
B = "# BEGIN k8s-ingress-dns (generated by scripts/render-ingress-dns.sh；勿手改)"
E = "# END k8s-ingress-dns"
managed = set(hosts)
out = []; skipping = False
for ln in open(f):
    s = ln.rstrip("\n")
    if s.strip() == B: skipping = True; continue
    if s.strip() == E: skipping = False; continue
    if skipping: continue
    toks = s.split()
    if toks and not s.lstrip().startswith("#"):
        ip, names = toks[0], toks[1:]
        names = [n for n in names if n not in managed]
        if not names:
            continue  # 该行只剩 IP（全是托管域名）→ 丢弃
        s = " ".join([ip] + names)
    out.append(s)
while out and out[-1] == "": out.pop()
out.append(B)
out.append(f"{vip} " + " ".join(hosts))
out.append(E)
shutil.copyfile(f, f + ".bak")
open(f, "w").write("\n".join(out) + "\n")
print(f"[+] 已更新 {f}（备份 {f}.bak）")
PY
fi

# ---------- 4) 可选：节点 /etc/hosts ----------
if [ "${UPDATE_NODE_HOSTS:-0}" = "1" ] && command -v kubectl >/dev/null 2>&1; then
  payload="$(printf '%s\n' "${HOSTS[@]}")"
  while read -r ip; do
    [ -z "$ip" ] && continue
    echo "[+] 同步节点 ${ip} 的 /etc/hosts"
    printf '%s\n' "$payload" | base64 -w0 | ssh -o StrictHostKeyChecking=no -o ConnectTimeout=8 root@"$ip" \
      "VIP='$VIP' B64=$(printf '%s' "$payload" | base64 -w0) bash -s" <<'NODE' || echo "    [!] 节点 $ip 同步失败"
VIP="$VIP"
B="# BEGIN k8s-ingress-dns (generated)"; E="# END k8s-ingress-dns"
python3 - "$VIP" "$B64" <<'PY'
import sys, shutil, base64
vip, b64 = sys.argv[1], sys.argv[2]
hosts = base64.b64decode(b64).decode().split()
managed = set(hosts)
f = "/etc/hosts"; B="# BEGIN k8s-ingress-dns (generated)"; E="# END k8s-ingress-dns"
out=[]; skip=False
for ln in open(f):
    s=ln.rstrip("\n")
    if s.strip()==B: skip=True; continue
    if s.strip()==E: skip=False; continue
    if skip: continue
    t=s.split()
    if t and not s.lstrip().startswith("#"):
        names=[n for n in t[1:] if n not in managed]
        if not names: continue
        s=" ".join([t[0]]+names)
    out.append(s)
while out and out[-1]=="": out.pop()
out += [B, f"{vip} "+" ".join(hosts), E]
shutil.copyfile(f, f+".bak")
open(f,"w").write("\n".join(out)+"\n")
print("    [ok] /etc/hosts 已更新")
PY
NODE
  done < <(kubectl get nodes -o jsonpath='{range .items[*]}{.status.addresses[?(@.type=="InternalIP")].address}{"\n"}{end}' 2>/dev/null)
fi

echo "[+] 入口 DNS 渲染完成"